### ISSUE TITLE
Update base to 4.5.3

### ISSUE THREAD

**Issue by JoshuaTheMiller** [JoshuaTheMiller/Terraria#5]
With release v4.5.3, TShock now support Terraria 1.4.2.3!

After some testing, the base image definition here should be updated to use this version by default.

More information can be found at the following: https://github.com/Pryaxis/TShock/releases/tag/v4.5.3

## TODO

- [x] Update default version ARG.
- [x] Add warning to README around blindly using "LATEST" image tag.
- [x] Add config file for GH Actions to generate multiple different versions of Docker images for consumption.
